CREATE TABLE kraken_ticker (
  id SERIAL PRIMARY KEY,
  exchange VARCHAR(120) NOT NULL DEFAULT 'kraken',
  timestamp BIGINT NOT NULL,
  ask_price NUMERIC,
  ask_lot_volume NUMERIC,
  ask_whole_lot_volume NUMERIC,
  bid_price NUMERIC,
  bid_lot_volume NUMERIC,
  bid_whole_lot_volume NUMERIC,
  close_price NUMERIC,
  close_lot_volume NUMERIC,
  volume_today NUMERIC,
  volume_24h NUMERIC,
  weighted_average_price NUMERIC,
  weighted_average_price_24h NUMERIC,
  number_of_trades INTEGER NOT NULL,
  number_of_trades_24h INTEGER NOT NULL,
  low_price NUMERIC,
  low_price_24h NUMERIC,
  high_price NUMERIC,
  high_price_24h NUMERIC,
  open_price NUMERIC,
  open_price_24h NUMERIC,
  pair VARCHAR(10) NOT NULL
);